export class AudioSystem{
 constructor(saveSystem){this.save=saveSystem;this.context=null;this.master=null;this.musicGain=null;this.sfxGain=null;this.musicTimer=0;this.step=0;}
 ensure(){if(this.context)return this.context;const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return null;this.context=new Ctx();this.master=this.context.createGain();this.musicGain=this.context.createGain();this.sfxGain=this.context.createGain();this.musicGain.connect(this.master);this.sfxGain.connect(this.master);this.master.connect(this.context.destination);this.applySettings();return this.context;}
 applySettings(){const settings=this.save.get().settings;if(!this.master)return;this.master.gain.value=settings.muted?0:1;this.musicGain.gain.value=settings.musicVolume;this.sfxGain.gain.value=settings.sfxVolume;}
 setMusicVolume(value){this.save.mutate(s=>{s.settings.musicVolume=Math.max(0,Math.min(1,value));});this.applySettings();}
 setSfxVolume(value){this.save.mutate(s=>{s.settings.sfxVolume=Math.max(0,Math.min(1,value));});this.applySettings();}
 toggleMute(){let muted=false;this.save.mutate(s=>{s.settings.muted=!s.settings.muted;muted=s.settings.muted;});this.applySettings();return muted;}
 tone(freq=440,duration=.08,type='square',volume=.16,when=0,target='sfx'){const ctx=this.ensure();if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),dest=target==='music'?this.musicGain:this.sfxGain;osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,ctx.currentTime+when);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+when+duration);osc.connect(gain);gain.connect(dest);osc.start(ctx.currentTime+when);osc.stop(ctx.currentTime+when+duration+.02);}
 play(name){const map={button:[520,.045,'square'],attack:[180,.07,'sawtooth'],magic:[660,.18,'sine'],gun:[120,.045,'square'],heal:[520,.25,'sine'],coin:[960,.08,'square'],chest:[440,.3,'triangle'],synth:[740,.45,'sine'],boss:[80,.5,'sawtooth'],hit:[110,.06,'square'],victory:[660,.5,'triangle'],defeat:[150,.5,'sawtooth']};const [f,d,t]=map[name]||map.button;this.tone(f,d,t,.18);if(name==='victory'||name==='synth'){this.tone(f*1.25,d*.8,t,.13,.12);this.tone(f*1.5,d*.7,t,.11,.22);}}
 startMusic(mode='battle'){this.stopMusic();this.ensure();const battle=[220,277,330,440,330,277],menu=[262,330,392,330,294,349];const notes=mode==='battle'?battle:menu;this.musicTimer=setInterval(()=>{const f=notes[this.step++%notes.length];this.tone(f,.32,'square',.045,0,'music');this.tone(f/2,.42,'triangle',.035,.02,'music');},420);}
 stopMusic(){clearInterval(this.musicTimer);this.musicTimer=0;}
}
