import { formatNumber } from '../utils/helpers.js';
export class TopBar{
 constructor(root,{save,heroSystem,modal,audio,onSettings}){this.root=root;this.save=save;this.heroes=heroSystem;this.modal=modal;this.audio=audio;this.onSettings=onSettings;this.render();}
 render(){const state=this.save.get(),player=state.player,power=this.heroes.teamPower(),next=Math.floor(100*Math.pow(player.level,1.2));this.root.innerHTML=`<div class="topbar pixel-frame"><div class="player-card pixel-frame"><div class="player-avatar"><div class="pixel-face"></div></div><div class="player-copy"><div class="player-name">${player.name}</div><div class="player-meta"><span>Lv. ${player.level}</span><span>⚔ ${formatNumber(Math.max(power,player.power||0))}</span><span>VIP ${player.vip}</span></div><div class="xp-bar"><div class="xp-fill" style="width:${Math.min(100,player.exp/next*100)}%"></div></div></div><div class="achievement">🏆</div></div><div class="resource-box pixel-frame"><div class="resource-main"><div class="resource-icon">●</div><span class="resource-value">${formatNumber(player.gold)}</span></div><button class="plus-btn" data-shop="gold">+</button></div><div class="resource-box pixel-frame"><div class="resource-main"><div class="resource-icon gem"><span>◆</span></div><span class="resource-value">${formatNumber(player.diamond)}</span></div><button class="plus-btn" data-shop="diamond">+</button></div><button class="icon-btn pixel-frame" data-top="notice">📜<span class="notif">!</span></button><button class="icon-btn pixel-frame" data-top="mail">✉</button><button class="icon-btn pixel-frame" data-top="settings">⚙</button></div>`;
 this.root.querySelectorAll('[data-shop]').forEach(btn=>btn.onclick=()=>{this.audio.play('button');this.modal.show({title:'Shop',body:`<p>${btn.dataset.shop==='gold'?'Gold':'Diamond'} shop uses game currency only.</p><p>Earn resources from battles, Bosses, chests and offline rewards.</p>`});});
 this.root.querySelector('[data-top="notice"]').onclick=()=>this.modal.show({title:'Notice',body:'<p>Every stage 10 is a Boss. Gunner unlocks in Chapter 3 and Holy Sword in Chapter 5.</p>'});
 this.root.querySelector('[data-top="mail"]').onclick=()=>this.modal.show({title:'Mail',body:'<p>No unclaimed mail.</p>'});
 this.root.querySelector('[data-top="settings"]').onclick=()=>this.onSettings?.();}
}
