import { heroes } from './data/heroes.js';
import { equipmentMap } from './data/equipment.js';
import { RARITIES,EQUIPMENT_SLOTS } from './config.js';
const rarityMap=Object.fromEntries(RARITIES.map(r=>[r.id,r]));
const glyph=slot=>({weapon:'⚔',helmet:'⛑',armor:'🛡',boots:'🥾',ring:'◉',necklace:'◇',gloves:'✊',belt:'▰',accessory:'✦'}[slot]||'◆');
const itemStats=item=>[['ATK',item.attack],['DEF',item.defense],['HP',item.hp],['CRIT',item.critRate?`${(item.critRate*100).toFixed(1)}%`:0],['CDMG',item.critDamage?`${(item.critDamage*100).toFixed(1)}%`:0],['ASPD',item.attackSpeed?item.attackSpeed.toFixed(2):0]].filter(([,v])=>v&&v!=='0.0%').map(([k,v])=>`${k} +${v}`).join('<br>')||'Balanced';
export function renderPage(ui,type){const root=document.getElementById('page-overlay-root');root.style.display='block';if(type==='heroes')renderHeroes(ui,root);else if(type==='bag')renderBag(ui,root);else if(type==='town')renderTown(ui,root);else if(type==='settings')renderSettings(ui,root);}
export function closePage(){const root=document.getElementById('page-overlay-root');root.innerHTML='';root.style.display='none';}
function head(title){return `<div class="page-heading"><h2>${title}</h2><button class="pixel-btn" data-page-close>Back to Battle</button></div>`;}
function bindClose(root){root.querySelector('[data-page-close]').onclick=closePage;}
function renderHeroes(ui,root){const state=ui.state.get();root.innerHTML=`<div class="page-overlay pixel-frame">${head('Heroes')}<div class="hero-detail-grid">${heroes.map(def=>{const hs=state.heroes[def.id],stats=ui.state.heroStats(def.id);return `<article class="hero-detail pixel-frame"><div class="hero-detail-top"><div class="hero-big-icon"><div class="hero-silhouette" style="transform:scale(2);transform-origin:top left;left:28px;top:22px;--hero-color:#e0aa82;--hero-armor:#${def.palette.armor.toString(16).padStart(6,'0')};--hero-accent:#${def.palette.accent.toString(16).padStart(6,'0')};--hero-hair:#${def.palette.hair.toString(16).padStart(6,'0')}"></div></div><div><h3>${def.name} · Lv.${hs.level} ${hs.unlocked?'':'🔒'}</h3><div class="stat-list">${def.role}<br>HP ${stats.hp}　MP ${stats.mp}<br>ATK ${stats.attack}　DEF ${stats.defense}<br>CRIT ${(stats.critRate*100).toFixed(1)}%　SPD ${stats.attackSpeed.toFixed(2)}<br>EXP ${hs.exp}/${Math.floor(70*Math.pow(hs.level,1.32))}</div><button class="pixel-btn ${state.party.includes(def.id)?'green':''}" data-party="${def.id}" ${hs.unlocked?'':'disabled'}>${state.party.includes(def.id)?'Remove from Party':'Add to Party'}</button></div></div><div class="equipment-grid">${Object.entries(hs.equipment).map(([slot,id])=>{const item=state.inventory.find(i=>i.uid===id),tpl=item&&equipmentMap[item.templateId];return `<div class="equipment-slot"><b>${slot}</b><br>${tpl?tpl.name:'Empty'}</div>`;}).join('')}</div><div class="skill-list">${def.skills.map(skill=>`<div class="skill-item ${hs.level<skill.level?'locked':''}"><b>${skill.name}</b> · Lv.${skill.level}<br>Energy ${skill.energy} · CD ${skill.cooldown}s</div>`).join('')}</div></article>`;}).join('')}</div></div>`;bindClose(root);root.querySelectorAll('[data-party]').forEach(btn=>btn.onclick=()=>{const result=ui.state.toggleParty(btn.dataset.party);if(!result.ok)ui.toast(result.msg);renderHeroes(ui,root);ui.render();});}
function renderBag(ui,root){const state=ui.state.get();ui.selectedHero=ui.selectedHero||state.party[0];root.innerHTML=`<div class="page-overlay pixel-frame">${head('Bag / Equipment')}<div class="inventory-toolbar"><select data-hero>${Object.entries(state.heroes).filter(([,h])=>h.unlocked).map(([id])=>`<option value="${id}" ${id===ui.selectedHero?'selected':''}>Equip to ${id}</option>`).join('')}</select><button class="pixel-btn" data-sort>Sort by Rarity</button></div><div class="inventory-grid">${[...state.inventory].sort((a,b)=>RARITIES.findIndex(r=>r.id===b.rarity)-RARITIES.findIndex(r=>r.id===a.rarity)||b.level-a.level).map(item=>{const tpl=equipmentMap[item.templateId],rarity=rarityMap[item.rarity],equipped=ui.state.isEquipped(item.uid);return `<article class="inventory-item ${item.locked?'locked-item':''}" style="--rarity-color:${rarity.color}"><div class="item-name">${glyph(tpl.slot)} ${tpl.name}</div><div class="item-rarity">${rarity.name} · ${rarity.label}</div><div class="stars">${'★'.repeat(rarity.stars)}</div><div class="item-stats">Lv.${item.level}<br>${itemStats(item)}<br>${equipped?'Equipped':'In Bag'}</div><div class="item-actions"><button data-equip="${item.uid}">Equip</button><button data-synth-item="${item.uid}">Synthesis</button></div></article>`;}).join('')}</div></div>`;bindClose(root);root.querySelector('[data-hero]').onchange=e=>ui.selectedHero=e.target.value;root.querySelectorAll('[data-equip]').forEach(btn=>btn.onclick=()=>{ui.toast(ui.state.equip(ui.selectedHero,btn.dataset.equip)?'Equipment equipped':'Cannot equip this item');renderBag(ui,root);ui.render();});root.querySelectorAll('[data-synth-item]').forEach(btn=>btn.onclick=()=>{ui.state.toggleSynth(btn.dataset.synthItem);closePage();ui.openSynthesis();});}
function renderTown(ui,root){root.innerHTML=`<div class="page-overlay pixel-frame">${head('Adventure Town')}<div class="town-scene"><article class="town-building pixel-frame"><strong>Blacksmith</strong><span>9-to-1 equipment synthesis.</span><button class="pixel-btn gold" data-town="synth">Open</button></article><article class="town-building pixel-frame"><strong>Hero Hall</strong><span>Manage heroes and equipment.</span><button class="pixel-btn green" data-town="heroes">Open</button></article><article class="town-building pixel-frame"><strong>General Store</strong><span>Earn equipment in automatic battles.</span><button class="pixel-btn" data-town="bag">Open Bag</button></article><article class="town-building pixel-frame"><strong>Guild Records</strong><span>Wins and defeated Bosses are saved locally.</span><button class="pixel-btn" data-town="records">View</button></article><article class="town-building pixel-frame"><strong>Settings</strong><span>Audio and local save management.</span><button class="pixel-btn" data-town="settings">Open</button></article></div></div>`;bindClose(root);root.querySelectorAll('[data-town]').forEach(btn=>btn.onclick=()=>{const type=btn.dataset.town;if(type==='synth'){closePage();ui.openSynthesis();}else if(type==='records'){const s=ui.state.get().stats;ui.modal('Guild Records',`<p>Victories: ${s.wins}<br>Defeats: ${s.losses}<br>Bosses defeated: ${s.bosses}</p>`);}else renderPage(ui,type);});}
function renderSettings(ui,root){root.innerHTML=`<div class="page-overlay pixel-frame">${head('Settings')}<div class="settings-list"><div class="settings-row pixel-frame"><label>Auto Mode</label><button class="pixel-btn green" data-auto>${ui.state.get().auto?'AUTO ON':'AUTO OFF'}</button><span></span></div><div class="settings-row pixel-frame"><label>Save Data</label><button class="pixel-btn" data-export>Import / Export</button><button class="pixel-btn red" data-reset>Reset</button></div></div></div>`;bindClose(root);root.querySelector('[data-auto]').onclick=()=>{ui.state.mutate(s=>s.auto=!s.auto);renderSettings(ui,root);ui.render();};root.querySelector('[data-export]').onclick=()=>ui.saveModal();root.querySelector('[data-reset]').onclick=()=>ui.confirm('Reset Save','This permanently deletes local progress.',()=>{ui.state.reset();location.reload();});}
