import { INITIAL_PLAYER,RARITIES,EQUIPMENT_SLOTS,MAX_OFFLINE_SECONDS,OFFLINE_RATES } from './config.js';
import { heroes } from './data/heroes.js';
import { equipmentCatalog,equipmentMap } from './data/equipment.js';
import { uid,choice,randomFloat,deepClone,safeJsonParse } from './utils/helpers.js';
const KEY='PixelIdleRPG.github.v1';
const rarityMap=Object.fromEntries(RARITIES.map(r=>[r.id,r]));
const heroSlots=()=>Object.fromEntries(EQUIPMENT_SLOTS.map(slot=>[slot,null]));
function initial(){const heroState={};heroes.forEach(h=>heroState[h.id]={level:1,exp:0,unlocked:h.unlocked,equipment:heroSlots()});const state={version:1,player:{...INITIAL_PLAYER},chapter:1,stage:1,maxChapter:1,maxStage:1,party:['fighter','mage'],heroes:heroState,inventory:[],synthesis:[],auto:true,lastSeen:Date.now(),offline:null,stats:{wins:0,losses:0,bosses:0}};for(let i=0;i<12;i++)state.inventory.push(createItem('common',1,'plate_armor'));for(let i=0;i<8;i++)state.inventory.push(createItem(i<5?'common':'uncommon',1+i%3));return state;}
function createItem(rarity='common',level=1,templateId=null){const template=templateId?equipmentMap[templateId]:choice(equipmentCatalog),r=rarityMap[rarity]||RARITIES[0],value=Math.max(1,Math.round((template.basePower+level*2.2)*r.multiplier*randomFloat(.88,1.14)));const item={uid:uid('eq'),templateId:template.id,rarity:r.id,level,locked:false,attack:0,defense:0,hp:0,critRate:0,critDamage:0,attackSpeed:0};if(template.mainStat==='attack')item.attack=value;if(template.mainStat==='defense')item.defense=value;if(template.mainStat==='hp')item.hp=value*7;if(template.mainStat==='critRate')item.critRate=value/1000;if(template.mainStat==='critDamage')item.critDamage=value/300;if(template.mainStat==='attackSpeed')item.attackSpeed=value/1200;return item;}
function sanitize(raw){const base=initial();if(!raw||typeof raw!=='object')return base;const out={...base,...raw,player:{...base.player,...raw.player},heroes:{...base.heroes,...raw.heroes},stats:{...base.stats,...raw.stats}};out.player.gold=Math.max(0,Number(out.player.gold)||0);out.player.diamond=Math.max(0,Number(out.player.diamond)||0);out.chapter=Math.max(1,Math.floor(Number(out.chapter)||1));out.stage=Math.max(1,Math.min(10,Math.floor(Number(out.stage)||1)));out.inventory=Array.isArray(out.inventory)?out.inventory.filter(i=>i&&equipmentMap[i.templateId]&&rarityMap[i.rarity]):base.inventory;out.party=Array.isArray(out.party)?out.party.filter(id=>out.heroes[id]?.unlocked).slice(0,2):base.party;if(!out.party.length)out.party=['fighter'];out.synthesis=Array.isArray(out.synthesis)?out.synthesis.slice(0,9):[];return out;}
export class AppState{
 constructor(){this.state=initial();this.listeners=new Set();}
 load(){this.state=sanitize(safeJsonParse(localStorage.getItem(KEY)));this.prepareOffline();this.save();return this.state;}
 get(){return this.state;}
 subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn);}
 notify(){this.listeners.forEach(fn=>fn(this.state));}
 save(){this.state.lastSeen=Date.now();localStorage.setItem(KEY,JSON.stringify(this.state));this.notify();}
 mutate(fn){fn(this.state);this.save();}
 reset(){localStorage.removeItem(KEY);this.state=initial();this.save();}
 export(){return JSON.stringify(this.state,null,2);}
 import(text){const parsed=safeJsonParse(text);if(!parsed||parsed.version!==1)return{ok:false,error:'Invalid save format'};this.state=sanitize(parsed);this.save();return{ok:true};}
 prepareOffline(){const now=Date.now(),seconds=Math.min(MAX_OFFLINE_SECONDS,Math.max(0,Math.floor((now-(this.state.lastSeen||now))/1000))),minutes=Math.floor(seconds/60);if(minutes>0)this.state.offline={id:uid('offline'),seconds,gold:minutes*OFFLINE_RATES.gold,diamond:minutes*OFFLINE_RATES.diamond,exp:minutes*OFFLINE_RATES.exp};}
 claimOffline(id){if(!this.state.offline||this.state.offline.id!==id)return false;const reward=this.state.offline;this.state.player.gold+=reward.gold;this.state.player.diamond+=reward.diamond;this.state.party.forEach(heroId=>this.gainExp(heroId,reward.exp,false));this.state.offline=null;this.save();return true;}
 gainExp(id,amount,save=true){const h=this.state.heroes[id];if(!h)return 0;let ups=0;h.exp+=Math.max(0,Math.floor(amount));while(h.exp>=Math.floor(70*Math.pow(h.level,1.32))){h.exp-=Math.floor(70*Math.pow(h.level,1.32));h.level++;ups++;}if(save)this.save();return ups;}
 heroStats(id){const def=heroes.find(h=>h.id===id),h=this.state.heroes[id];if(!def||!h)return null;const growth=1+(h.level-1)*.105,stats={...def.base,hp:Math.round(def.base.hp*growth),attack:Math.round(def.base.attack*growth),defense:Math.round(def.base.defense*growth)};Object.values(h.equipment).forEach(itemId=>{const item=this.state.inventory.find(i=>i.uid===itemId);if(item){stats.hp+=item.hp||0;stats.attack+=item.attack||0;stats.defense+=item.defense||0;stats.critRate+=item.critRate||0;stats.critDamage+=item.critDamage||0;stats.attackSpeed+=item.attackSpeed||0;}});return stats;}
 toggleParty(id){const h=this.state.heroes[id];if(!h?.unlocked)return{ok:false,msg:'Hero locked'};const i=this.state.party.indexOf(id);if(i>=0){if(this.state.party.length===1)return{ok:false,msg:'At least one hero required'};this.state.party.splice(i,1);}else{if(this.state.party.length>=2)return{ok:false,msg:'Party maximum is two'};this.state.party.push(id);}this.save();return{ok:true};}
 equip(heroId,itemId){const item=this.state.inventory.find(i=>i.uid===itemId),tpl=item&&equipmentMap[item.templateId],hero=this.state.heroes[heroId];if(!item||!tpl||!hero?.unlocked)return false;if(tpl.allowedHeroes&&!tpl.allowedHeroes.includes(heroId))return false;Object.values(this.state.heroes).forEach(h=>Object.entries(h.equipment).forEach(([slot,id])=>{if(id===itemId)h.equipment[slot]=null;}));hero.equipment[tpl.slot]=itemId;this.save();return true;}
 toggleSynth(itemId){const item=this.state.inventory.find(i=>i.uid===itemId);if(!item||item.locked||this.isEquipped(itemId))return false;const i=this.state.synthesis.indexOf(itemId);if(i>=0)this.state.synthesis.splice(i,1);else if(this.state.synthesis.length<9)this.state.synthesis.push(itemId);this.save();return true;}
 autoSelect(rarity){this.state.synthesis=this.state.inventory.filter(i=>i.rarity===rarity&&!i.locked&&!this.isEquipped(i.uid)).slice(0,9).map(i=>i.uid);this.save();return this.state.synthesis.length;}
 synthesize(){const items=this.state.synthesis.map(id=>this.state.inventory.find(i=>i.uid===id)).filter(Boolean);if(items.length!==9)return{ok:false,msg:'Select 9 items'};const rarity=items[0].rarity;if(!items.every(i=>i.rarity===rarity))return{ok:false,msg:'Items must share rarity'};const r=rarityMap[rarity];if(!r.next)return{ok:false,msg:'Mythic is maximum'};if(this.state.player.gold<r.cost)return{ok:false,msg:'Not enough Gold'};const ids=new Set(items.map(i=>i.uid)),result=createItem(r.next,Math.max(...items.map(i=>i.level)),items[0].templateId);this.state.player.gold-=r.cost;this.state.inventory=this.state.inventory.filter(i=>!ids.has(i.uid));this.state.inventory.push(result);this.state.synthesis=[];this.save();return{ok:true,item:result,cost:r.cost};}
 isEquipped(id){return Object.values(this.state.heroes).some(h=>Object.values(h.equipment).includes(id));}
 reward(stageDef){const boss=stageDef.boss,gold=Math.round((boss?900:90)*(1+stageDef.chapter*.12)),exp=Math.round((boss?320:70)*(1+stageDef.chapter*.1));this.state.player.gold+=gold;this.state.party.forEach(id=>this.gainExp(id,exp,false));const drop=createItem(boss?'rare':Math.random()<.2?'uncommon':'common',(stageDef.chapter-1)*10+stageDef.stage);this.state.inventory.push(drop);this.state.stats.wins++;if(boss)this.state.stats.bosses++;this.save();return{gold,exp,drop};}
 advance(){if(this.state.stage<10){this.state.stage++;this.state.maxStage=Math.max(this.state.maxStage,this.state.stage);}else{this.state.chapter++;this.state.stage=1;this.state.maxChapter=Math.max(this.state.maxChapter,this.state.chapter);heroes.forEach(h=>{if(this.state.chapter>=h.unlockChapter)this.state.heroes[h.id].unlocked=true;});}this.save();}
}
export const appState=new AppState();
