import { heroes } from './data/heroes.js';
import { equipmentMap } from './data/equipment.js';
import { RARITIES } from './config.js';
import { formatNumber,formatDuration } from './utils/helpers.js';
import { renderPage,closePage } from './appPages.js';
const rarityMap=Object.fromEntries(RARITIES.map(r=>[r.id,r]));
export class AppUI{
 constructor(state){this.state=state;this.selectedHero='fighter';this.skillCallback=()=>{};this.nextCallback=()=>{};this.toastTimer=0;this.state.subscribe(()=>this.render());this.bindRoots();this.render();}
 bindRoots(){this.top=document.getElementById('topbar-root');this.side=document.getElementById('sidemenu-root');this.bottom=document.getElementById('bottommenu-root');this.hud=document.getElementById('battlehud-root');this.right=document.getElementById('rightpanel-root');this.modalRoot=document.getElementById('modal-root');this.toastRoot=document.getElementById('toast-root');}
 setBattleCallbacks({onSkill,onNext}){this.skillCallback=onSkill||this.skillCallback;this.nextCallback=onNext||this.nextCallback;}
 render(){this.renderTop();this.renderSide();this.renderBottom();this.renderHUD();this.renderSynthesis();}
 renderTop(){const s=this.state.get(),p=s.player,next=Math.floor(100*Math.pow(p.level,1.2));this.top.innerHTML=`<div class="topbar pixel-frame"><div class="player-card pixel-frame"><div class="player-avatar"><div class="pixel-face"></div></div><div class="player-copy"><div class="player-name">${p.name}</div><div class="player-meta"><span>Lv. ${p.level}</span><span>⚔ ${formatNumber(p.power)}</span><span>VIP ${p.vip}</span></div><div class="xp-bar"><div class="xp-fill" style="width:${Math.min(100,p.exp/next*100)}%"></div></div></div><div class="achievement">🏆</div></div><div class="resource-box pixel-frame"><div class="resource-main"><div class="resource-icon">●</div><span class="resource-value">${formatNumber(p.gold)}</span></div><button class="plus-btn" data-store="Gold">+</button></div><div class="resource-box pixel-frame"><div class="resource-main"><div class="resource-icon gem"><span>◆</span></div><span class="resource-value">${formatNumber(p.diamond)}</span></div><button class="plus-btn" data-store="Diamond">+</button></div><button class="icon-btn pixel-frame" data-top="notice">📜<span class="notif">!</span></button><button class="icon-btn pixel-frame" data-top="mail">✉</button><button class="icon-btn pixel-frame" data-top="settings">⚙</button></div>`;this.top.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>this.modal('Shop',`<p>${b.dataset.store} can be earned from battles, chests and offline rewards.</p>`));this.top.querySelector('[data-top="notice"]').onclick=()=>this.modal('Notice','<p>Every stage 10 is a Boss. Gunner unlocks in Chapter 3 and Holy Sword in Chapter 5.</p>');this.top.querySelector('[data-top="mail"]').onclick=()=>this.modal('Mail','<p>No unclaimed mail.</p>');this.top.querySelector('[data-top="settings"]').onclick=()=>renderPage(this,'settings');}
 renderSide(){const items=[['Shop','▣'],['Events','🎁'],['Pass','♛'],['Quests','▤'],['Mail','✉'],['Rank','🏆']];this.side.innerHTML=`<div class="side-menu pixel-frame">${items.map(([name,icon],i)=>`<button class="side-btn" data-side="${name}"><span class="side-icon">${icon}</span><span>${name}</span>${[1,2,3].includes(i)?'<span class="notif">!</span>':''}</button>`).join('')}</div>`;this.side.querySelectorAll('[data-side]').forEach(btn=>btn.onclick=()=>this.modal(btn.dataset.side,`<p>${btn.dataset.side} is available as a local offline feature panel.</p>`));}
 renderBottom(){const items=[['Town','🏰','town'],['Heroes','🧙','heroes'],['Bag','🎒','bag'],['Battle','⚔','battle'],['Dungeon','🌀','battle'],['Guild','🛡','town']];this.bottom.innerHTML=`<div class="bottom-menu pixel-frame">${items.map(([name,icon,page])=>`<button class="bottom-btn ${name==='Battle'?'active':''}" data-page="${page}"><span class="nav-icon">${icon}</span><span>${name}</span></button>`).join('')}</div>`;this.bottom.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{if(btn.dataset.page==='battle')closePage();else renderPage(this,btn.dataset.page);});}
 renderHUD(){const s=this.state.get();this.hud.innerHTML=`<button class="pixel-btn open-synth-mobile" data-open-synth>9合1</button><div class="battle-hud pixel-frame"><div class="hero-strip">${heroes.map(def=>{const hs=s.heroes[def.id],selected=s.party.includes(def.id),stats=this.state.heroStats(def.id);return `<button class="hero-chip ${selected?'selected':''} ${hs.unlocked?'':'locked'}" data-hero="${def.id}" ${hs.unlocked?'':'disabled'}><div class="hero-icon"><div class="hero-silhouette" style="--hero-color:#e0aa82;--hero-armor:#${def.palette.armor.toString(16).padStart(6,'0')};--hero-accent:#${def.palette.accent.toString(16).padStart(6,'0')};--hero-hair:#${def.palette.hair.toString(16).padStart(6,'0')}"></div></div><div class="hero-chip-copy"><div class="hero-chip-name">${def.name}</div><div class="tiny-bar"><div class="tiny-fill" style="width:100%"></div></div><div class="tiny-bar"><div class="tiny-fill energy" style="width:100%"></div></div></div></button>`;}).join('')}</div><div class="skill-strip">${this.skillsHTML()}<button class="auto-btn ${s.auto?'':'off'}" data-auto>AUTO ${s.auto?'ON':'OFF'}</button><button class="stage-btn" data-next>NEXT STAGE</button></div></div>`;this.hud.querySelectorAll('[data-hero]').forEach(btn=>btn.onclick=()=>{const result=this.state.toggleParty(btn.dataset.hero);if(!result.ok)this.toast(result.msg);});this.hud.querySelectorAll('[data-skill]').forEach(btn=>btn.onclick=()=>this.skillCallback(Number(btn.dataset.skill)));this.hud.querySelector('[data-auto]').onclick=()=>this.state.mutate(x=>x.auto=!x.auto);this.hud.querySelector('[data-next]').onclick=()=>this.nextCallback();this.hud.querySelector('[data-open-synth]').onclick=()=>this.openSynthesis();}
 skillsHTML(){const s=this.state.get(),heroId=s.party[0],def=heroes.find(h=>h.id===heroId),hs=s.heroes[heroId];return def.skills.map((skill,i)=>`<button class="skill-btn ${hs.level>=skill.level?'ready':'locked'}" data-skill="${i}" ${hs.level>=skill.level?'':'disabled'}><div class="skill-title">${skill.name}</div><div class="skill-meta">Energy ${skill.energy} · CD ${skill.cooldown}s</div></button>`).join('');}
 openSynthesis(){this.right.classList.add('open');this.renderSynthesis();}
 renderSynthesis(){const s=this.state.get(),selected=s.synthesis.map(id=>s.inventory.find(i=>i.uid===id)).filter(Boolean),rarity=selected[0]?.rarity||'common',r=rarityMap[rarity],candidates=s.inventory.filter(i=>i.rarity===rarity&&!i.locked&&!this.state.isEquipped(i.uid));this.right.innerHTML=`<div class="right-panel pixel-frame"><button class="pixel-btn drawer-toggle" data-close-drawer>✕</button><div><div class="panel-title">EQUIPMENT SYNTHESIS</div><div class="rule-text">Combine 9 items of the same rarity<br>to get 1 item of the next rarity!</div></div><div class="synth-grid">${Array.from({length:9},(_,i)=>{const item=selected[i],tpl=item&&equipmentMap[item.templateId];return `<button class="synth-slot ${item?'selected':''}" data-remove="${item?.uid||''}"><span class="synth-slot-index">${i+1}</span>${item?`<span title="${tpl.name}">${this.glyph(tpl.slot)}</span>`:'＋'}</button>`;}).join('')}</div><div><div class="synth-result"><div class="result-preview">${r.next?this.glyph(equipmentMap[selected[0]?.templateId]?.slot):'—'}</div><div class="result-copy">${selected.length}/9 selected<br>${r.name} ${'★'.repeat(r.stars)}<br>Cost ${formatNumber(r.cost||0)} Gold</div></div><div class="rarity-tabs">${RARITIES.filter(x=>x.next).map(x=>`<button class="rarity-filter ${x.id===rarity?'active':''}" style="--rarity-color:${x.color}" data-rarity="${x.id}">${x.name}</button>`).join('')}</div><div class="synth-actions"><button class="pixel-btn" data-auto-select>AUTO SELECT</button><button class="pixel-btn gold" data-synthesize>SYNTHESIZE</button></div><p class="rule-text">Available ${r.name}: ${candidates.length}</p></div></div>`;this.right.querySelector('[data-close-drawer]').onclick=()=>this.right.classList.remove('open');this.right.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{if(btn.dataset.remove)this.state.toggleSynth(btn.dataset.remove);});this.right.querySelectorAll('[data-rarity]').forEach(btn=>btn.onclick=()=>{this.state.autoSelect(btn.dataset.rarity);});this.right.querySelector('[data-auto-select]').onclick=()=>this.toast(`Selected ${this.state.autoSelect(rarity)}/9`);this.right.querySelector('[data-synthesize]').onclick=()=>{const result=this.state.synthesize();this.toast(result.ok?`Created ${rarityMap[result.item.rarity].name} equipment`:result.msg);};}
 glyph(slot){return({weapon:'⚔',helmet:'⛑',armor:'🛡',boots:'🥾',ring:'◉',necklace:'◇',gloves:'✊',belt:'▰',accessory:'✦'}[slot]||'◆');}
 toast(message){clearTimeout(this.toastTimer);this.toastRoot.innerHTML=`<div class="toast pixel-frame">${message}</div>`;requestAnimationFrame(()=>this.toastRoot.firstElementChild?.classList.add('show'));this.toastTimer=setTimeout(()=>this.toastRoot.innerHTML='',1900);}
 modal(title,body,actions='<button class="pixel-btn gold" data-close-modal>OK</button>'){this.modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal-card pixel-frame"><div class="modal-heading"><h3>${title}</h3><button class="pixel-btn" data-close-modal>✕</button></div><div class="modal-body">${body}</div><div class="modal-actions">${actions}</div></div></div>`;this.modalRoot.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>this.modalRoot.innerHTML='');}
 confirm(title,body,onConfirm){this.modal(title,body,'<button class="pixel-btn" data-close-modal>Cancel</button><button class="pixel-btn red" data-confirm>Confirm</button>');this.modalRoot.querySelector('[data-confirm]').onclick=()=>{this.modalRoot.innerHTML='';onConfirm();};}
 saveModal(){this.modal('Import / Export Save','<p>Copy JSON to back up your local progress.</p><textarea class="save-textarea" id="save-json"></textarea>','<button class="pixel-btn" data-export>Export</button><button class="pixel-btn green" data-import>Import</button><button class="pixel-btn" data-close-modal>Close</button>');const area=this.modalRoot.querySelector('#save-json');this.modalRoot.querySelector('[data-export]').onclick=()=>{area.value=this.state.export();area.select();};this.modalRoot.querySelector('[data-import]').onclick=()=>{const result=this.state.import(area.value);this.toast(result.ok?'Save imported':result.error);if(result.ok)setTimeout(()=>location.reload(),500);};}
 showOffline(){const reward=this.state.get().offline;if(!reward)return;this.modal('Idle Rewards',`<p>Offline time: <b>${formatDuration(reward.seconds)}</b></p><p>Gold +${formatNumber(reward.gold)}<br>Diamond +${formatNumber(reward.diamond)}<br>EXP +${formatNumber(reward.exp)}</p>`,'<button class="pixel-btn gold" data-claim>Claim</button>');this.modalRoot.querySelector('[data-claim]').onclick=()=>{if(this.state.claimOffline(reward.id)){this.modalRoot.innerHTML='';this.toast('Offline rewards claimed');}};}
}
