import Phaser from 'https://cdn.jsdelivr.net/npm/phaser@3.90.0/dist/phaser.esm.js';
import { getStageDefinition } from './data/stages.js';
import { heroes } from './data/heroes.js';
import { enemyMap } from './data/enemies.js';
import { calculateDamage,randomFloat } from './utils/helpers.js';
const byId=id=>heroes.find(h=>h.id===id);
export class PixelBattleScene extends Phaser.Scene{
 constructor(){super('PixelBattleScene');this.entities=[];this.heroUnits=[];this.enemyUnits=[];this.running=false;this.finished=false;this.damagePool=[];this.effectPool=[];}
 create(){this.state=this.registry.get('appState');this.ui=this.registry.get('appUI');this.drawWorld();this.createPools();this.ui.setBattleCallbacks({onSkill:index=>this.manualSkill(index),onNext:()=>this.nextStage()});this.startStage();this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.cleanup());}
 drawWorld(){const {width,height}=this.scale,g=this.add.graphics().setDepth(-20);g.fillGradientStyle(0x3d78ad,0x3d78ad,0x9cc9e4,0x9cc9e4,1);g.fillRect(0,0,width,height);g.fillStyle(0x6279a4,1);g.fillTriangle(0,400,230,150,480,400);g.fillTriangle(300,400,620,110,900,400);g.fillTriangle(700,400,1040,160,1280,400);g.fillStyle(0x45794b,1);for(let x=0;x<width;x+=105){g.fillRect(x,245+(x%210)/5,24,220);g.fillCircle(x+12,235+(x%210)/5,56);}g.fillStyle(0x9aa5b3,1);for(let x=90;x<width;x+=210){g.fillRect(x,290,34,160);g.fillRect(x+55,270,34,180);g.fillRect(x-10,270,110,24);}g.fillStyle(0x6d8f47,1);g.fillRect(0,445,width,275);g.fillStyle(0x806448,1);g.fillTriangle(0,720,0,535,350,500);g.fillTriangle(0,720,1280,720,930,500);g.fillRect(350,500,580,220);for(let i=0;i<30;i++){g.fillStyle(i%2?0x8e7958:0x5e7d3f,1);g.fillRect((i*79)%1280,490+(i*43)%210,8+(i%4)*3,5);}}
 createPools(){for(let i=0;i<24;i++){const t=this.add.text(0,0,'',{fontFamily:'monospace',fontSize:'22px',fontStyle:'bold',stroke:'#000',strokeThickness:4}).setOrigin(.5).setVisible(false).setDepth(50);this.damagePool.push(t);}for(let i=0;i<20;i++){const c=this.add.circle(0,0,8,0xffffff).setVisible(false).setDepth(30);this.effectPool.push(c);}}
 stageHeader(){this.header?.destroy(true);this.header=this.add.container(640,42).setDepth(60);const s=this.state.get();this.header.add(this.add.text(0,-22,`Chapter ${s.chapter} - Stage ${s.stage}/10`,{fontFamily:'monospace',fontSize:'23px',fontStyle:'bold',color:'#f6df9b',stroke:'#000',strokeThickness:5}).setOrigin(.5));for(let i=1;i<=10;i++){const x=-250+(i-1)*55,current=i===s.stage,boss=i===10;this.header.add(this.add.polygon(x,20,[[0,-14],[14,0],[0,14],[-14,0]],boss?0xa93e4b:current?0xf0c95c:i<s.stage?0x70c94d:0x344057,1).setStrokeStyle(3,current?0xffffff:0x111722));this.header.add(this.add.text(x,20,boss?'☠':String(i),{fontFamily:'monospace',fontStyle:'bold',fontSize:boss?'17px':'12px',color:'#fff'}).setOrigin(.5));if(i<10)this.header.add(this.add.rectangle(x+28,20,30,5,i<s.stage?0x70c94d:0x263147));}this.header.add(this.add.text(0,58,'☠ Stage 10 is BOSS!',{fontFamily:'monospace',fontStyle:'bold',fontSize:'14px',color:'#ffb260',backgroundColor:'#19141b',padding:{x:8,y:4}}).setOrigin(.5));}
 clearUnits(){this.entities.forEach(e=>e.container.destroy(true));this.entities=[];this.heroUnits=[];this.enemyUnits=[];this.chest?.destroy(true);this.chest=null;}
 startStage(){this.clearUnits();this.stageHeader();this.finished=false;this.running=false;const s=this.state.get(),stage=getStageDefinition(s.chapter,s.stage);this.stageDef=stage;if(stage.boss){this.cameras.main.shake(650,.012);this.ui.modal('BOSS WARNING',`<p>A powerful Boss approaches: <b>${enemyMap[stage.enemies[0].id].name}</b></p>`,'<button class="pixel-btn red" data-fight>FIGHT</button>');document.querySelector('[data-fight]').onclick=()=>{document.getElementById('modal-root').innerHTML='';this.spawn(stage);};}else this.spawn(stage);}
 spawn(stage){this.running=true;const s=this.state.get();s.party.forEach((id,i)=>this.heroUnits.push(this.createHero(id,185+i*135,500-i*38)));stage.enemies.forEach((info,i)=>this.enemyUnits.push(this.createEnemy(info,900+i*105,470+i*42)));this.entities=[...this.heroUnits,...this.enemyUnits];this.ui.render();}
 createHero(id,x,y){const def=byId(id),stats=this.state.heroStats(id),unit=this.makeUnit({x,y,side:'hero',color:def.palette.armor,accent:def.palette.accent,hair:def.palette.hair,weapon:def.palette.weapon,boss:false,name:def.name});return Object.assign(unit,{id,def,hp:stats.hp,maxHp:stats.hp,mp:stats.mp,maxMp:stats.mp,attack:stats.attack,defense:stats.defense,critRate:stats.critRate,critDamage:stats.critDamage,attackSpeed:stats.attackSpeed,moveSpeed:stats.moveSpeed,range:stats.attackRange,attackTimer:randomFloat(.1,.55),skillTimer:randomFloat(2.5,4.5),alive:true,shield:0});}
 createEnemy(info,x,y){const def=enemyMap[info.id],stats={hp:Math.round(def.base.hp*info.hpScale),attack:Math.round(def.base.attack*info.attackScale),defense:Math.round(def.base.defense*info.hpScale*.72),attackSpeed:def.base.attackSpeed,moveSpeed:def.base.moveSpeed,attackRange:def.base.attackRange};const unit=this.makeUnit({x,y,side:'enemy',color:def.color,accent:def.type==='boss'?0x5b1822:0x344222,hair:def.color,weapon:0xd6d6d6,boss:def.type==='boss',name:def.name});return Object.assign(unit,{id:def.id,def,hp:stats.hp,maxHp:stats.hp,attack:stats.attack,defense:stats.defense,attackSpeed:stats.attackSpeed,moveSpeed:stats.moveSpeed,range:stats.attackRange,attackTimer:randomFloat(.4,1),skillTimer:def.skill?.cooldown||999,alive:true,shield:0});}
 makeUnit({x,y,side,color,accent,hair,weapon,boss,name}){const c=this.add.container(x,y).setDepth(Math.round(y));const shadow=this.add.ellipse(0,32,boss?85:58,boss?20:14,0x000000,.32);const scale=boss?1.45:1;const body=this.add.rectangle(0,0,32*scale,38*scale,color).setStrokeStyle(3,0x111111);const head=this.add.rectangle(0,-31*scale,25*scale,24*scale,0xe2ad82).setStrokeStyle(3,0x111111);const hairShape=this.add.rectangle(0,-43*scale,28*scale,9*scale,hair);const arm=this.add.rectangle(side==='hero'?21:-21,-2,9,27,accent).setStrokeStyle(2,0x111111);const weaponShape=this.add.rectangle(side==='hero'?32:-32,-6,5,boss?50:38,weapon).setOrigin(.5,.8).setRotation(side==='hero'?.4:-.4);const leg1=this.add.rectangle(-9,28,9,25,accent).setStrokeStyle(2,0x111111),leg2=this.add.rectangle(9,28,9,25,accent).setStrokeStyle(2,0x111111);const hpBg=this.add.rectangle(0,-64*scale,boss?130:76,9,0x0b0d12).setStrokeStyle(1,0xffffff,.35),hpBar=this.add.rectangle(-(boss?126:72)/2,-64*scale,boss?126:72,5,side==='hero'?0x67d154:0xe45961).setOrigin(0,.5);const label=this.add.text(0,-79*scale,name,{fontFamily:'monospace',fontSize:boss?'14px':'11px',color:'#fff',stroke:'#000',strokeThickness:3}).setOrigin(.5);c.add([shadow,body,head,hairShape,arm,weaponShape,leg1,leg2,hpBg,hpBar,label]);this.tweens.add({targets:c,y:y-4,duration:700,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});return{container:c,shadow,body,head,arm,weaponShape,leg1,leg2,hpBar,hpWidth:boss?126:72,side,boss};}
 update(time,delta){if(!this.running||this.finished)return;const dt=Math.min(.05,delta/1000);this.heroUnits.filter(u=>u.alive).forEach(u=>this.tickUnit(u,this.enemyUnits,dt));this.enemyUnits.filter(u=>u.alive).forEach(u=>this.tickUnit(u,this.heroUnits,dt));if(this.enemyUnits.every(e=>!e.alive))this.victory();else if(this.heroUnits.every(h=>!h.alive))this.defeat();}
 tickUnit(unit,targets,dt){const living=targets.filter(t=>t.alive);if(!living.length)return;let target=living.reduce((best,t)=>Math.abs(t.container.x-unit.container.x)<Math.abs(best.container.x-unit.container.x)?t:best,living[0]);const dist=Math.abs(target.container.x-unit.container.x);unit.attackTimer-=dt;unit.skillTimer-=dt;if(dist>unit.range){const direction=Math.sign(target.container.x-unit.container.x);unit.container.x+=direction*unit.moveSpeed*dt;unit.leg1.y=28+Math.sin(performance.now()*.02)*3;unit.leg2.y=28-Math.sin(performance.now()*.02)*3;}else if(unit.attackTimer<=0){this.attack(unit,target);unit.attackTimer=1/Math.max(.2,unit.attackSpeed);}if(unit.side==='hero'&&this.state.get().auto&&unit.skillTimer<=0){this.castSkill(unit,0);unit.skillTimer=unit.def.skills[0].cooldown;}if(unit.side==='enemy'&&unit.boss&&unit.skillTimer<=0){this.bossSkill(unit);unit.skillTimer=unit.def.skill.cooldown;}}
 attack(attacker,target){this.tweens.add({targets:attacker.weaponShape,rotation:attacker.side==='hero'?-1.1:1.1,duration:100,yoyo:true});const critical=attacker.side==='hero'&&Math.random()<(attacker.critRate||0),damage=calculateDamage({attack:attacker.attack,defense:target.defense,multiplier:1,critical,criticalDamage:attacker.critDamage||1.5});this.time.delayedCall(90,()=>this.applyDamage(target,damage,critical,attacker.side==='enemy'));this.flash(attacker.side==='hero'?'attack':'hit');}
 applyDamage(target,damage,critical=false,enemyDamage=false){if(!target.alive)return;const absorb=Math.min(damage,target.shield||0);target.shield=Math.max(0,(target.shield||0)-absorb);damage=Math.max(0,damage-absorb);target.hp=Math.max(0,target.hp-damage);target.hpBar.width=target.hpWidth*(target.hp/target.maxHp);this.floatText(target.container.x,target.container.y-70,absorb?'BLOCK':critical?`CRIT ${damage}`:`${damage}`,absorb?'#86cfff':enemyDamage?'#ff6877':critical?'#ffd45e':'#ffffff',critical?28:21);this.tweens.add({targets:target.container,x:target.container.x+(target.side==='hero'?-7:7),duration:55,yoyo:true});if(target.hp<=0)this.kill(target);}
 kill(unit){unit.alive=false;this.tweens.add({targets:unit.container,alpha:0,y:unit.container.y+24,angle:unit.side==='hero'?-10:10,duration:500,onComplete:()=>unit.container.setVisible(false)});}
 manualSkill(index){const hero=this.heroUnits.find(h=>h.alive);if(!this.running||!hero)return this.ui.toast('Battle is not ready');this.castSkill(hero,index);}
 castSkill(unit,index){const skill=unit.def.skills[index];if(!skill||this.state.get().heroes[unit.id].level<skill.level)return this.ui.toast('Skill is locked');const targets=this.enemyUnits.filter(e=>e.alive);if(!targets.length)return;this.tweens.add({targets:unit.container,scaleX:1.12,scaleY:1.12,duration:120,yoyo:true});if(skill.type==='heal'||skill.type==='groupHeal'){const allies=this.heroUnits.filter(h=>h.alive).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp),list=skill.type==='groupHeal'?allies:allies.slice(0,1);list.forEach(ally=>{const heal=Math.round(unit.attack*skill.multiplier);ally.hp=Math.min(ally.maxHp,ally.hp+heal);ally.hpBar.width=ally.hpWidth*(ally.hp/ally.maxHp);this.floatText(ally.container.x,ally.container.y-70,`+${heal}`,'#6ee780',24);this.effect(ally.container.x,ally.container.y,0x75d64d,32);});return;}if(skill.type==='shield'||skill.type==='teamShield'){const allies=skill.type==='teamShield'?this.heroUnits.filter(h=>h.alive):[unit];allies.forEach(ally=>{ally.shield=Math.round(ally.maxHp*skill.shield);this.effect(ally.container.x,ally.container.y,0x6bcaff,38);});return;}const hitTargets=['aoe','multi'].includes(skill.type)?targets:[targets[0]];hitTargets.forEach((target,i)=>this.time.delayedCall(i*80,()=>{const critical=Math.random()<unit.critRate,damage=calculateDamage({attack:unit.attack,defense:target.defense,multiplier:skill.multiplier||1,critical,criticalDamage:unit.critDamage});this.projectile(unit,target,skill.effect,()=>this.applyDamage(target,damage,critical,false));}));}
 projectile(from,to,effect,onHit){const color=effect==='heal'?0x75d64d:effect==='bullet'?0xffd45e:effect==='holy'||effect==='divine'?0xfff09a:0xb96cff,p=this.add.circle(from.container.x,from.container.y-25,effect==='bullet'?5:10,color).setDepth(40);this.tweens.add({targets:p,x:to.container.x,y:to.container.y-20,duration:220,onComplete:()=>{p.destroy();this.effect(to.container.x,to.container.y-15,color,effect==='explosion'||effect==='meteor'?45:24);onHit();}});}
 bossSkill(unit){this.cameras.main.shake(500,.009);this.floatText(unit.container.x,unit.container.y-120,unit.def.skill.name,'#ff6574',25);this.time.delayedCall(unit.def.skill.warning*1000,()=>this.heroUnits.filter(h=>h.alive).forEach(h=>this.applyDamage(h,calculateDamage({attack:unit.attack,defense:h.defense,multiplier:unit.def.skill.multiplier}),false,true)));}
 effect(x,y,color,radius){const c=this.effectPool.find(e=>!e.visible);if(!c)return;c.setPosition(x,y).setRadius(8).setFillStyle(color,.75).setVisible(true).setScale(.5).setAlpha(1);this.tweens.add({targets:c,scale:radius/8,alpha:0,duration:320,onComplete:()=>c.setVisible(false)});}
 floatText(x,y,text,color,size=22){const t=this.damagePool.find(d=>!d.visible);if(!t)return;t.setPosition(x,y).setText(text).setColor(color).setFontSize(size).setVisible(true).setAlpha(1);this.tweens.add({targets:t,y:y-45,alpha:0,duration:700,onComplete:()=>t.setVisible(false)});}
 flash(sound){this.registry.get('audio')?.play?.(sound);}
 victory(){if(this.finished)return;this.finished=true;this.running=false;const reward=this.state.reward(this.stageDef);this.registry.get('audio')?.play?.('victory');this.spawnChest(reward);this.ui.modal('Victory',`<p>Gold +${reward.gold}<br>EXP +${reward.exp}<br>Equipment: ${reward.drop.rarity}</p>`,'<button class="pixel-btn gold" data-victory-next>Next Stage</button>');document.querySelector('[data-victory-next]').onclick=()=>{document.getElementById('modal-root').innerHTML='';this.state.advance();this.startStage();};}
 defeat(){if(this.finished)return;this.finished=true;this.running=false;this.state.mutate(s=>s.stats.losses++);this.registry.get('audio')?.play?.('defeat');this.ui.modal('Defeat','<p>Upgrade heroes or change equipment, then try again.</p>','<button class="pixel-btn red" data-retry>Retry</button>');document.querySelector('[data-retry]').onclick=()=>{document.getElementById('modal-root').innerHTML='';this.startStage();};}
 spawnChest(reward){this.chest=this.add.container(720,520).setDepth(45);const box=this.add.rectangle(0,0,70,48,0xa85e22).setStrokeStyle(5,0xf4c75e),lid=this.add.rectangle(0,-24,76,20,0xd58a2d).setStrokeStyle(4,0xffdf78),lock=this.add.rectangle(0,0,13,18,0xffdf78);this.chest.add([box,lid,lock]);this.chest.setSize(90,80).setInteractive({useHandCursor:true}).on('pointerdown',()=>{this.registry.get('audio')?.play?.('chest');this.floatText(this.chest.x,this.chest.y-60,`+${reward.gold} GOLD`,'#ffd45e',22);this.tweens.add({targets:lid,y:-42,angle:-8,duration:180});});this.tweens.add({targets:this.chest,y:510,duration:600,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});}
 nextStage(){if(this.running)return this.ui.toast('Battle is already running');if(this.finished){this.state.advance();this.startStage();}else this.startStage();}
 cleanup(){this.running=false;this.clearUnits();}
}
